version: "3.8"

services:
  postgresdb:
    image: postgres:latest
    container_name: slicecraft_db
    restart: always
    environment:
      POSTGRES_PASSWORD: slicecraftpassword
      POSTGRES_USER: admin
      POSTGRES_DB: slicecraft
    ports:
      - "5433:5432"
    networks:
      - slicecraft_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: slicecraft_backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=postgresdb
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASS=slicecraftpassword
      - DB_NAME=slicecraft
      - PORT=3001
      - SECRET_KEY=slicecraft_jwt_secret_key_12345
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - postgresdb
    networks:
      - slicecraft_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: slicecraft_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - BACKEND_URL=http://backend:3001
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/pages:/app/pages
      - ./frontend/public:/app/public
      - ./frontend/styles:/app/styles
    depends_on:
      - backend
    networks:
      - slicecraft_net

networks:
  slicecraft_net:
    driver: bridge
